In [3]:
#꼭 알아야 되는 패키지
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
#0으로 초기화된 배열

arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#빈값으로 만들어진 배열

arr=np.empty((4,4))
print(arr)

[[1.14246317e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [7]:
#1로 가득찬 배열을 만든다

arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#배열의 생성

arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
#ndarray 배열의 모양,차수,데이터 타입확인

arr=np.array([[1,2,3],[4,5,6]])#[[]] 꺽세 2개니 2차원
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
arr.shape



(2, 3)

In [15]:
arr.ndim

2

In [16]:
arr.dtype

dtype('int64')

In [17]:
arr_float=arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [20]:
arr_str=np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [21]:
arr_int=arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [22]:
#ndarray 배열의 연산

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

In [23]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [25]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [26]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [27]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [28]:
#ndarray 배열 슬라이싱 하기

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
arr_1=arr[:2,1:3]# :2>>vertically only 0,1 position
                #1:3>> horizontally only 1,2 position
print(arr_1)

[[2 3]
 [5 6]]


In [34]:
arr[0,2]

3

In [35]:
arr[[0,1,2],[2,0,1]]#첫번째는 vertical의 에서, 뒤에는 요소에서...vertical,horizontal


array([3, 4, 8])

In [36]:
idx=arr>3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [37]:
print(arr[idx])

[4 5 6 7 8 9]


In [39]:
redwine=np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [41]:
#sum
print(redwine.sum())

152084.78194


In [42]:
#average

print(redwine.mean())

7.926036165311652


In [44]:
#axis

print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [45]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [47]:
redwine[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [48]:
redwine[:,0].mean()

8.31963727329581

In [51]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [52]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])